//
// RatingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RatingAPI {

    /**
     Get Product Rating
     
     - parameter productId: (path) Product ID. 
     - parameter contentType: (header) Describes the type of the content being sent. 
     - parameter accept: (header) HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getProductRating(productId: String, contentType: String, accept: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: GetProductRating200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getProductRatingWithRequestBuilder(productId: productId, contentType: contentType, accept: accept).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Product Rating
     - GET /rating/{productId}
     - Retrieves the rating of a specific product.
     - API Key:
       - type: apiKey X-VTEX-API-AppToken (HEADER)
       - name: appToken
     - API Key:
       - type: apiKey X-VTEX-API-AppKey (HEADER)
       - name: appKey
     - parameter productId: (path) Product ID. 
     - parameter contentType: (header) Describes the type of the content being sent. 
     - parameter accept: (header) HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand. 
     - returns: RequestBuilder<GetProductRating200Response> 
     */
    open class func getProductRatingWithRequestBuilder(productId: String, contentType: String, accept: String) -> RequestBuilder<GetProductRating200Response> {
        var localVariablePath = "/rating/{productId}"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{productId}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": contentType.encodeToJSON(),
            "Accept": accept.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetProductRating200Response>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
