//
// EditReviewRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct EditReviewRequest: Codable, JSONEncodable, Hashable {

    /** Review's locale. */
    public var locale: String?
    /** Product ID. */
    public var productId: String
    /** Customer rating. */
    public var rating: Double
    /** Reviewer name. */
    public var reviewerName: String
    /** Shopper email. */
    public var shopperId: String?
    /** Review's text. */
    public var text: String
    /** Review's title. */
    public var title: String
    /** If the reviewer is a verified purchaser (`true`) or not (`false`). */
    public var verifiedPurchaser: Bool?

    public init(locale: String? = nil, productId: String, rating: Double, reviewerName: String, shopperId: String? = nil, text: String, title: String, verifiedPurchaser: Bool? = nil) {
        self.locale = locale
        self.productId = productId
        self.rating = rating
        self.reviewerName = reviewerName
        self.shopperId = shopperId
        self.text = text
        self.title = title
        self.verifiedPurchaser = verifiedPurchaser
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locale
        case productId
        case rating
        case reviewerName
        case shopperId
        case text
        case title
        case verifiedPurchaser
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encode(productId, forKey: .productId)
        try container.encode(rating, forKey: .rating)
        try container.encode(reviewerName, forKey: .reviewerName)
        try container.encodeIfPresent(shopperId, forKey: .shopperId)
        try container.encode(text, forKey: .text)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(verifiedPurchaser, forKey: .verifiedPurchaser)
    }
}

