//
// GetalistofReviews200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetalistofReviews200Response: Codable, JSONEncodable, Hashable {

    /** Array of reviews. */
    public var data: [GetalistofReviews200ResponseDataInner]?
    public var range: GetalistofReviews200ResponseRange?

    public init(data: [GetalistofReviews200ResponseDataInner]? = nil, range: GetalistofReviews200ResponseRange? = nil) {
        self.data = data
        self.range = range
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case range
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(range, forKey: .range)
    }
}

