//
// GetProductRating200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetProductRating200Response: Codable, JSONEncodable, Hashable {

    /** Avarage rating of the product. */
    public var average: Double?
    /** Total amount of ranting of the product. */
    public var totalCount: Double?

    public init(average: Double? = nil, totalCount: Double? = nil) {
        self.average = average
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case average
        case totalCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(average, forKey: .average)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
    }
}

