//
// Name.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Name: Codable, JSONEncodable, Hashable {

    public var firstname: String
    public var lastname: String

    public init(firstname: String, lastname: String) {
        self.firstname = firstname
        self.lastname = lastname
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstname
        case lastname
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(firstname, forKey: .firstname)
        try container.encode(lastname, forKey: .lastname)
    }
}

