//
// Product.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Product: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var title: String
    public var description: String?
    public var price: Double
    public var category: String?
    public var image: String?

    public init(id: Int, title: String, description: String? = nil, price: Double, category: String? = nil, image: String? = nil) {
        self.id = id
        self.title = title
        self.description = description
        self.price = price
        self.category = category
        self.image = image
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case description
        case price
        case category
        case image
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(price, forKey: .price)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(image, forKey: .image)
    }
}

