//
// SaveReviewRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SaveReviewRequest: Codable, JSONEncodable, Hashable {

    /** Product ID. */
    public var productId: String
    /** Customer rating. */
    public var rating: Int
    /** Reviewer name. */
    public var reviewerName: String
    /** Review's text. */
    public var text: String
    /** Review's title. */
    public var title: String

    public init(productId: String, rating: Int, reviewerName: String, text: String, title: String) {
        self.productId = productId
        self.rating = rating
        self.reviewerName = reviewerName
        self.text = text
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productId
        case rating
        case reviewerName
        case text
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(productId, forKey: .productId)
        try container.encode(rating, forKey: .rating)
        try container.encode(reviewerName, forKey: .reviewerName)
        try container.encode(text, forKey: .text)
        try container.encode(title, forKey: .title)
    }
}

