//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct User: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var email: String
    public var username: String
    public var password: String
    public var name: Name

    public init(id: Int, email: String, username: String, password: String, name: Name) {
        self.id = id
        self.email = email
        self.username = username
        self.password = password
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case username
        case password
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(email, forKey: .email)
        try container.encode(username, forKey: .username)
        try container.encode(password, forKey: .password)
        try container.encode(name, forKey: .name)
    }
}

